version: "3.9"

services:
  db:
    container_name: db_app
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - mynetwork
  ml:
    container_name: ml_app
    build: ./ml-app
    restart: unless-stopped
    ports:
      - $ML_LOCAL_PORT:$ML_DOCKER_PORT
    networks:
      - mynetwork
  backend:
    container_name: backend_app
    depends_on:
      - db
      - ml
    build: ./backend-app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=db
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - DB_PORT=$NODE_LOCAL_PORT
    stdin_open: true
    tty: true
    networks:
      - mynetwork

volumes:
  db:

networks:
  mynetwork:
